/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const GarmentType = IDL.Variant({
  'cap' : IDL.Null,
  'poloShirt' : IDL.Null,
  'pufferJacket' : IDL.Null,
  'backpack' : IDL.Null,
  'shorts' : IDL.Null,
  'joggers' : IDL.Null,
  'tankTop' : IDL.Null,
  'toteBag' : IDL.Null,
  'leggings' : IDL.Null,
  'duffleBag' : IDL.Null,
  'vNeckShirt' : IDL.Null,
  'tShirt' : IDL.Null,
  'fannyPack' : IDL.Null,
  'skirt' : IDL.Null,
  'beanie' : IDL.Null,
  'canvasPoster' : IDL.Null,
  'crewNeck' : IDL.Null,
  'zipUpHoodie' : IDL.Null,
  'hoodie' : IDL.Null,
  'sportsJersey' : IDL.Null,
  'dress' : IDL.Null,
  'sweatpants' : IDL.Null,
  'longSleeveShirt' : IDL.Null,
});
export const Color = IDL.Record({
  'red' : IDL.Nat8,
  'blue' : IDL.Nat8,
  'green' : IDL.Nat8,
});
export const TextLayer = IDL.Record({
  'rotation' : IDL.Float64,
  'shadow' : IDL.Record({
    'blurRadius' : IDL.Float64,
    'color' : Color,
    'offsetX' : IDL.Float64,
    'offsetY' : IDL.Float64,
  }),
  'color' : Color,
  'text' : IDL.Text,
  'isBold' : IDL.Bool,
  'isItalic' : IDL.Bool,
  'isUnderline' : IDL.Bool,
  'textSpacing' : IDL.Nat,
  'fontFamily' : IDL.Text,
  'position' : IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
  'fontSize' : IDL.Nat,
});
export const Design = IDL.Record({
  'id' : IDL.Text,
  'owner' : IDL.Principal,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'garmentType' : GarmentType,
  'updatedAt' : IDL.Int,
  'textLayers' : IDL.Vec(TextLayer),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDesign' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDesign' : IDL.Func([IDL.Text], [Design], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
  'renameDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDesign' : IDL.Func(
      [IDL.Text, IDL.Text, GarmentType, IDL.Vec(TextLayer)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const GarmentType = IDL.Variant({
    'cap' : IDL.Null,
    'poloShirt' : IDL.Null,
    'pufferJacket' : IDL.Null,
    'backpack' : IDL.Null,
    'shorts' : IDL.Null,
    'joggers' : IDL.Null,
    'tankTop' : IDL.Null,
    'toteBag' : IDL.Null,
    'leggings' : IDL.Null,
    'duffleBag' : IDL.Null,
    'vNeckShirt' : IDL.Null,
    'tShirt' : IDL.Null,
    'fannyPack' : IDL.Null,
    'skirt' : IDL.Null,
    'beanie' : IDL.Null,
    'canvasPoster' : IDL.Null,
    'crewNeck' : IDL.Null,
    'zipUpHoodie' : IDL.Null,
    'hoodie' : IDL.Null,
    'sportsJersey' : IDL.Null,
    'dress' : IDL.Null,
    'sweatpants' : IDL.Null,
    'longSleeveShirt' : IDL.Null,
  });
  const Color = IDL.Record({
    'red' : IDL.Nat8,
    'blue' : IDL.Nat8,
    'green' : IDL.Nat8,
  });
  const TextLayer = IDL.Record({
    'rotation' : IDL.Float64,
    'shadow' : IDL.Record({
      'blurRadius' : IDL.Float64,
      'color' : Color,
      'offsetX' : IDL.Float64,
      'offsetY' : IDL.Float64,
    }),
    'color' : Color,
    'text' : IDL.Text,
    'isBold' : IDL.Bool,
    'isItalic' : IDL.Bool,
    'isUnderline' : IDL.Bool,
    'textSpacing' : IDL.Nat,
    'fontFamily' : IDL.Text,
    'position' : IDL.Record({ 'x' : IDL.Float64, 'y' : IDL.Float64 }),
    'fontSize' : IDL.Nat,
  });
  const Design = IDL.Record({
    'id' : IDL.Text,
    'owner' : IDL.Principal,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'garmentType' : GarmentType,
    'updatedAt' : IDL.Int,
    'textLayers' : IDL.Vec(TextLayer),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDesign' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDesign' : IDL.Func([IDL.Text], [Design], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyDesigns' : IDL.Func([], [IDL.Vec(Design)], ['query']),
    'renameDesign' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDesign' : IDL.Func(
        [IDL.Text, IDL.Text, GarmentType, IDL.Vec(TextLayer)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };