/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Color { 'red' : number, 'blue' : number, 'green' : number }
export interface Design {
  'id' : string,
  'owner' : Principal,
  'name' : string,
  'createdAt' : bigint,
  'garmentType' : GarmentType,
  'updatedAt' : bigint,
  'textLayers' : Array<TextLayer>,
}
export type GarmentType = { 'cap' : null } |
  { 'poloShirt' : null } |
  { 'pufferJacket' : null } |
  { 'backpack' : null } |
  { 'shorts' : null } |
  { 'joggers' : null } |
  { 'tankTop' : null } |
  { 'toteBag' : null } |
  { 'leggings' : null } |
  { 'duffleBag' : null } |
  { 'vNeckShirt' : null } |
  { 'tShirt' : null } |
  { 'fannyPack' : null } |
  { 'skirt' : null } |
  { 'beanie' : null } |
  { 'canvasPoster' : null } |
  { 'crewNeck' : null } |
  { 'zipUpHoodie' : null } |
  { 'hoodie' : null } |
  { 'sportsJersey' : null } |
  { 'dress' : null } |
  { 'sweatpants' : null } |
  { 'longSleeveShirt' : null };
export interface TextLayer {
  'rotation' : number,
  'shadow' : {
    'blurRadius' : number,
    'color' : Color,
    'offsetX' : number,
    'offsetY' : number,
  },
  'color' : Color,
  'text' : string,
  'isBold' : boolean,
  'isItalic' : boolean,
  'isUnderline' : boolean,
  'textSpacing' : bigint,
  'fontFamily' : string,
  'position' : { 'x' : number, 'y' : number },
  'fontSize' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDesign' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDesign' : ActorMethod<[string], Design>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyDesigns' : ActorMethod<[], Array<Design>>,
  'renameDesign' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDesign' : ActorMethod<
    [string, string, GarmentType, Array<TextLayer>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];