/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TextLayer {
    rotation: number;
    shadow: {
        blurRadius: number;
        color: Color;
        offsetX: number;
        offsetY: number;
    };
    color: Color;
    text: string;
    isBold: boolean;
    isItalic: boolean;
    isUnderline: boolean;
    textSpacing: bigint;
    fontFamily: string;
    position: {
        x: number;
        y: number;
    };
    fontSize: bigint;
}
export interface Design {
    id: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    garmentType: GarmentType;
    updatedAt: bigint;
    textLayers: Array<TextLayer>;
}
export interface UserProfile {
    name: string;
}
export interface Color {
    red: number;
    blue: number;
    green: number;
}
export enum GarmentType {
    cap = "cap",
    poloShirt = "poloShirt",
    pufferJacket = "pufferJacket",
    backpack = "backpack",
    shorts = "shorts",
    joggers = "joggers",
    tankTop = "tankTop",
    toteBag = "toteBag",
    leggings = "leggings",
    duffleBag = "duffleBag",
    vNeckShirt = "vNeckShirt",
    tShirt = "tShirt",
    fannyPack = "fannyPack",
    skirt = "skirt",
    beanie = "beanie",
    canvasPoster = "canvasPoster",
    crewNeck = "crewNeck",
    zipUpHoodie = "zipUpHoodie",
    hoodie = "hoodie",
    sportsJersey = "sportsJersey",
    dress = "dress",
    sweatpants = "sweatpants",
    longSleeveShirt = "longSleeveShirt"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteDesign(id: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDesign(id: string): Promise<Design>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listMyDesigns(): Promise<Array<Design>>;
    renameDesign(id: string, newName: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveDesign(id: string, name: string, garmentType: GarmentType, textLayers: Array<TextLayer>): Promise<void>;
}
import type { Design as _Design, GarmentType as _GarmentType, TextLayer as _TextLayer, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteDesign(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDesign(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDesign(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDesign(arg0: string): Promise<Design> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesign(arg0);
                return from_candid_Design_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesign(arg0);
            return from_candid_Design_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listMyDesigns(): Promise<Array<Design>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyDesigns();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyDesigns();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async renameDesign(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameDesign(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameDesign(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveDesign(arg0: string, arg1: string, arg2: GarmentType, arg3: Array<TextLayer>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveDesign(arg0, arg1, to_candid_GarmentType_n11(this._uploadFile, this._downloadFile, arg2), arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveDesign(arg0, arg1, to_candid_GarmentType_n11(this._uploadFile, this._downloadFile, arg2), arg3);
            return result;
        }
    }
}
function from_candid_Design_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Design): Design {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_GarmentType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GarmentType): GarmentType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    garmentType: _GarmentType;
    updatedAt: bigint;
    textLayers: Array<_TextLayer>;
}): {
    id: string;
    owner: Principal;
    name: string;
    createdAt: bigint;
    garmentType: GarmentType;
    updatedAt: bigint;
    textLayers: Array<TextLayer>;
} {
    return {
        id: value.id,
        owner: value.owner,
        name: value.name,
        createdAt: value.createdAt,
        garmentType: from_candid_GarmentType_n8(_uploadFile, _downloadFile, value.garmentType),
        updatedAt: value.updatedAt,
        textLayers: value.textLayers
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cap: null;
} | {
    poloShirt: null;
} | {
    pufferJacket: null;
} | {
    backpack: null;
} | {
    shorts: null;
} | {
    joggers: null;
} | {
    tankTop: null;
} | {
    toteBag: null;
} | {
    leggings: null;
} | {
    duffleBag: null;
} | {
    vNeckShirt: null;
} | {
    tShirt: null;
} | {
    fannyPack: null;
} | {
    skirt: null;
} | {
    beanie: null;
} | {
    canvasPoster: null;
} | {
    crewNeck: null;
} | {
    zipUpHoodie: null;
} | {
    hoodie: null;
} | {
    sportsJersey: null;
} | {
    dress: null;
} | {
    sweatpants: null;
} | {
    longSleeveShirt: null;
}): GarmentType {
    return "cap" in value ? GarmentType.cap : "poloShirt" in value ? GarmentType.poloShirt : "pufferJacket" in value ? GarmentType.pufferJacket : "backpack" in value ? GarmentType.backpack : "shorts" in value ? GarmentType.shorts : "joggers" in value ? GarmentType.joggers : "tankTop" in value ? GarmentType.tankTop : "toteBag" in value ? GarmentType.toteBag : "leggings" in value ? GarmentType.leggings : "duffleBag" in value ? GarmentType.duffleBag : "vNeckShirt" in value ? GarmentType.vNeckShirt : "tShirt" in value ? GarmentType.tShirt : "fannyPack" in value ? GarmentType.fannyPack : "skirt" in value ? GarmentType.skirt : "beanie" in value ? GarmentType.beanie : "canvasPoster" in value ? GarmentType.canvasPoster : "crewNeck" in value ? GarmentType.crewNeck : "zipUpHoodie" in value ? GarmentType.zipUpHoodie : "hoodie" in value ? GarmentType.hoodie : "sportsJersey" in value ? GarmentType.sportsJersey : "dress" in value ? GarmentType.dress : "sweatpants" in value ? GarmentType.sweatpants : "longSleeveShirt" in value ? GarmentType.longSleeveShirt : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Design>): Array<Design> {
    return value.map((x)=>from_candid_Design_n6(_uploadFile, _downloadFile, x));
}
function to_candid_GarmentType_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GarmentType): _GarmentType {
    return to_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GarmentType): {
    cap: null;
} | {
    poloShirt: null;
} | {
    pufferJacket: null;
} | {
    backpack: null;
} | {
    shorts: null;
} | {
    joggers: null;
} | {
    tankTop: null;
} | {
    toteBag: null;
} | {
    leggings: null;
} | {
    duffleBag: null;
} | {
    vNeckShirt: null;
} | {
    tShirt: null;
} | {
    fannyPack: null;
} | {
    skirt: null;
} | {
    beanie: null;
} | {
    canvasPoster: null;
} | {
    crewNeck: null;
} | {
    zipUpHoodie: null;
} | {
    hoodie: null;
} | {
    sportsJersey: null;
} | {
    dress: null;
} | {
    sweatpants: null;
} | {
    longSleeveShirt: null;
} {
    return value == GarmentType.cap ? {
        cap: null
    } : value == GarmentType.poloShirt ? {
        poloShirt: null
    } : value == GarmentType.pufferJacket ? {
        pufferJacket: null
    } : value == GarmentType.backpack ? {
        backpack: null
    } : value == GarmentType.shorts ? {
        shorts: null
    } : value == GarmentType.joggers ? {
        joggers: null
    } : value == GarmentType.tankTop ? {
        tankTop: null
    } : value == GarmentType.toteBag ? {
        toteBag: null
    } : value == GarmentType.leggings ? {
        leggings: null
    } : value == GarmentType.duffleBag ? {
        duffleBag: null
    } : value == GarmentType.vNeckShirt ? {
        vNeckShirt: null
    } : value == GarmentType.tShirt ? {
        tShirt: null
    } : value == GarmentType.fannyPack ? {
        fannyPack: null
    } : value == GarmentType.skirt ? {
        skirt: null
    } : value == GarmentType.beanie ? {
        beanie: null
    } : value == GarmentType.canvasPoster ? {
        canvasPoster: null
    } : value == GarmentType.crewNeck ? {
        crewNeck: null
    } : value == GarmentType.zipUpHoodie ? {
        zipUpHoodie: null
    } : value == GarmentType.hoodie ? {
        hoodie: null
    } : value == GarmentType.sportsJersey ? {
        sportsJersey: null
    } : value == GarmentType.dress ? {
        dress: null
    } : value == GarmentType.sweatpants ? {
        sweatpants: null
    } : value == GarmentType.longSleeveShirt ? {
        longSleeveShirt: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
